name: Escaneo Gitleaks

on:
  push:
    branches: [ "main" ]

jobs:
  check-leaks:
    runs-on: ubuntu-latest

    steps:
    - name: Comprueba repositorio
      uses: actions/checkout@v3

    - name: Instalar Gitleaks
      run: |
        sudo apt-get update
        sudo apt-get install gitleaks

    - name: Comprueba si hay fugas
      run: gitleaks detect --source . -v
