name: Escaneo Gitleaks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Comprueba repositorio
        uses: actions/checkout@v3

      - name: Comprueba si hay fugas.
        run:
          gitleaks detect --source . -v
