name: Escaneo Gitleaks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Comprueba repo
        uses: actions/checkout@v3

      - name: Ejecutar Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
