name: Escaneo Gitleaks

on:
  push:
    branches: [ "main" ]

jobs:
  check-leaks:
    runs-on: ubuntu-latest

    steps:
    - name: Comprueba repositorio
      uses: actions/checkout@v2

    - name: Comprueba si hay fugas.
      run:
        gitleaks detect --source . -v
